### PR TITLE
Timeout for image creation in config

### PR DESCRIPTION
**Pull request by Sorrowwill**
Hello,

We are currently working with quite large images in Linode (~20 GB) and often experience timeouts during image creation. I've added a timeout configuration variable so we can increase it for our workflow.

Could you please review this pull request and provide any comments or suggestions? If everything looks good, please consider merging it.

Thank you!

### CODE REVIEW

**Review by lgarber-akamai — CHANGES_REQUESTED** [review]
Thanks for the contribution! This PR looks great.

Just for consistency, could you add a corresponding test for the new field? 
See: https://github.com/linode/packer-plugin-linode/blob/main/builder/linode/builder_test.go#L254

**Comment by Sorrowwill** [comment]
> @Sorrowwill Thanks for the contribution! This PR looks great.
> 
> Just for consistency, could you add a corresponding test for the new field? See: https://github.com/linode/packer-plugin-linode/blob/main/builder/linode/builder_test.go#L254

Thank you for your time.
I have added a new test based on the example you provided.
Can you review this pull request again?

**Review by lgarber-akamai — APPROVED** [review]
LGTM!

**Comment by Sorrowwill** [comment]
Sorry, I noticed a typo that I made in the documentation and updated the pull request with the fix.

``` image_creation_timeout -> image_create_timeout```

**Review by yec-akamai — APPROVED** [review]

**Comment by Sorrowwill** [comment]
Hello, @lgarber-akamai 

Could we please proceed with the merge, or is it still waiting for something?)

**Comment by lgarber-akamai** [comment]
@Sorrowwill Sorry for the delay! This change has been merged and I'll let you know once it's out in a release.

**Pull request merged**
